### PR TITLE
chore: update `wgpu` 0.20.0 → 23.0.0

### PR DESCRIPTION
**Pull request by ErichDonGubler**

### CODE REVIEW

**Comment by fornwall** [comment]
Thanks!

Will look into the CI failures unrelated to this change.

**Comment by ErichDonGubler** [comment]
@fornwall: Has this been deployed? I'm still seeing failures when I open <https://wgpu-game-of-life.fornwall.net/>, and I'm concerned that this didn't fix what I intended (and am at a loss why it wouldn't 💦).

**Comment by fornwall** [comment]
@ErichDonGubler It should be.

I've played around with a service worker to try to get an offline experience and might have made a mistake there, so that you're seeing an outdated cached version. Could you check that (e.g. https://jun711.github.io/web/how-to-force-update-a-service-worker-on-chrome-firefox-and-safari/#firefox)?

**Comment by ErichDonGubler** [comment]
Ah, that WFM now, nice! TIL more about service workers.

**Pull request merged**
